### ISSUE TITLE
Can't resolve 'react-moment-proptypes'

### ISSUE THREAD

**Issue by santanaruben** [thiagozanetti/react-moment-countdown#163]
./node_modules/react-moment-countdown/dist/index.js
Module not found: Can't resolve 'react-moment-proptypes' in '...\node_modules\react-moment-countdown\dist'

**Comment by santanaruben** [comment]
Am I doing something wrong? I just used it one of the repo examples.

**Comment by thiagozanetti** [comment]
Hey @santanaruben! Thanks for reaching out.

I need to check it. I'll come back to you when I have something.

**Comment by Alwyn-RM** [comment]
If you install react-moment-proptypes in your project it's fixed. Maybe it's because your package lists it under devDependencies 

`npm install react-moment-proptypes`

**Comment by rever96** [comment]
try add a file named global.d.ts under src folder:

```declare module 'react-moment-countdown';```
