### ISSUE TITLE
fromDate prop?

### ISSUE THREAD

**Issue by Angelo8828** [thiagozanetti/react-moment-countdown#8]
Hello,

First of all, sorry because I am new to using React / React Native.

A colleague used this [forked package](https://github.com/adeb6600/react-native-moment-countdown) in our mobile app. There is no issue board in that forked package so I thought to write the issue here.

In computers and mobile devices, there is an option in the settings to manually change the time of the device. Our problem is that when the user exactly does that, the countdown adjusts. Although it is just an UI issue and I can still check if the requests are valid in the API server, it still annoys our users (and they are right to be annoyed). To solve the problem, I'm thinking that a fromDate prop is needed but sadly, we have none.

Help will be greatly appreciated, thanks.

**Comment by thiagozanetti** [comment]
Since you guys are using a forked project, I suggest you to reach the maintainer of that package to sort this out. Best of luck and thanks!
